import type { Metadata } from "next";

import "./globals.css";
import ContextProvider from "@/Provider/ContextProvider";
import UserContext from "@/Provider/UserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics Script */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-T1RWXJ9B4T"
        ></script>
        <script>
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-T1RWXJ9B4T');
          `}
        </script>
      </head>
      <body className={` antialiased`}>
        <ContextProvider>
          <UserContext>{children}</UserContext>
        </ContextProvider>
        <script
          type="text/javascript"
          src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
        ></script>
      </body>
    </html>
  );
}
