import type { Metadata } from "next";

import "./globals.css";
import ContextProvider from "@/Provider/ContextProvider";
import UserContext from "@/Provider/UserContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <ContextProvider>
          <UserContext>
            {children}
          </UserContext>
        </ContextProvider>
      </body>
    </html>
  );
}
