// Page.tsx
import Banner from '@/components/HomePage/Banner';
import Featured from '@/components/HomePage/Featured';
import PopularEvents from '@/components/HomePage/PopularEvents';
import TopEvents from '@/components/HomePage/TopEvents';
import { Metadata } from 'next';
import React from 'react';
export const metadata: Metadata = {
    title: "Home Page",
    description: "Generated by create next app",
};

const Page = async () => {
    return (
        <>
            <Banner />
            <div className='start-center flex-col gap-24 mt-24'>
                {/* <TodaysEvent /> */}
                <TopEvents />
                <PopularEvents />
                <Featured />
            </div>
        </>
    );
};



export default Page;
