// Page.tsx
import Banner from "@/components/HomePage/Banner";
import Featured from "@/components/HomePage/Featured";
import PopularEvents from "@/components/HomePage/PopularEvents";
import TopEvents from "@/components/HomePage/TopEvents";
import Spiner from "@/components/shared/Client/Spiner";
import { Spin } from "antd";
import { Metadata } from "next";
import React, { Suspense } from "react";
export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

const Page = async () => {
  return (
    <>
      <Suspense fallback={<Spiner />}>
        <Banner />
      </Suspense>
      <div className="start-center flex-col gap-24 mt-24">
        <Suspense fallback={<Spiner />}>
          <TopEvents />
        </Suspense>
        <Suspense fallback={<Spiner />}>
          <PopularEvents />
        </Suspense>
        <Suspense fallback={<Spiner />}>
          <Featured />
        </Suspense>
      </div>
    </>
  );
};

export default Page;
