// Page.tsx
import Banner from '@/components/HomePage/Banner';
import Featured from '@/components/HomePage/Featured';
import PopularEvents from '@/components/HomePage/PopularEvents';
import TopEvents from '@/components/HomePage/TopEvents';
import { Spin } from 'antd';
import { Metadata } from 'next';
import React, { Suspense } from 'react';
export const metadata: Metadata = {
    title: "Home Page",
    description: "Generated by create next app",
};

const Page = async () => {
    return (
        <>
            <Suspense fallback={<Spin />}>
                <Banner />
            </Suspense>
            <div className='start-center flex-col gap-24 mt-24'>
                <Suspense fallback={<Spin />}>
                    <TopEvents />
                </Suspense>
                <Suspense fallback={<Spin />}>
                    <PopularEvents />
                </Suspense>
                <Suspense fallback={<Spin />}>
                    <Featured />
                </Suspense>
            </div>
        </>
    );
};



export default Page;
